### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by gregbenner** [nodegui/nodegui-starter#133]
`❯ npm start    

> nodegui-starter@1.0.0 start /home/gnb/Sites/nodegui-starter
> webpack && qode ./dist/index.js

Hash: deac9f31aa19c3210b8b
Version: webpack 4.44.1
Time: 1958ms
Built at: 08/09/2020 8:34:21 PM
                                             Asset      Size  Chunks             Chunk Names
                                          index.js  1.72 MiB    main  [emitted]  main
nodegui_core-5dfc8dfcc3ef18a9aa8eb23dec633264.node  6.81 MiB          [emitted]  
Entrypoint main = index.js
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {main} [built]
[./src/index.js] 4.05 KiB {main} [built]
[crypto] external "crypto" 42 bytes {main} [built]
[events] external "events" 42 bytes {main} [built]
[fs] external "fs" 42 bytes {main} [built]
[os] external "os" 42 bytes {main} [built]
[path] external "path" 42 bytes {main} [built]
    + 246 hidden modules
webpack:///./src/index.js?:85
generateButton.addEventListener(QPushButtonEvents.clicked, () => {
                                                  ^

TypeError: Cannot read property 'clicked' of undefined
    at eval (webpack:///./src/index.js?:85:51)
    at Object../src/index.js (/home/gnb/Sites/nodegui-starter/dist/index.js:3039:1)
    at __webpack_require__ (/home/gnb/Sites/nodegui-starter/dist/index.js:20:30)
    at /home/gnb/Sites/nodegui-starter/dist/index.js:84:18
    at Object.<anonymous> (/home/gnb/Sites/nodegui-starter/dist/index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegui-starter@1.0.0 start: `webpack && qode ./dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegui-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gnb/.npm/_logs/2020-08-10T00_34_22_549Z-debug.log`

**Comment by gregbenner** [comment]
seems resloved in updated repo
