### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by x1yy** [nodegui/nodegui-starter#205]
when i run npm install, its failed. here is the error
```

> @nodegui/qode@2.1.0 postinstall /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/qode
> node install.js

Cached archive already exists at /home/dwi/.cache/qode-nodejs/qode-linux-x64-v2.1.0.tar.gz. Skipping download....
Extracting /home/dwi/.cache/qode-nodejs/qode-linux-x64-v2.1.0.tar.gz to /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/qode/binaries ...
Qode was setup successfully at : /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/qode/binaries

> @nodegui/nodegui@0.30.1 postinstall /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/nodegui
> cross-env npm run setupqt && (node ./scripts/skip.js || npm run build:addon)


> @nodegui/nodegui@0.30.1 setupqt /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/nodegui
> cross-env node ./scripts/setupMiniQt.js

Minimal Qt 5.14.1 setup:
Archive already exists at /home/dwi/.cache/nodegui-mini-qt-nodejs/5.14.1-0-202001240953icu-linux-Rhel7.2-x64.7z. Skipping download....
Extracting /home/dwi/.cache/nodegui-mini-qt-nodejs/5.14.1-0-202001240953icu-linux-Rhel7.2-x64.7z to /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/nodegui/miniqt ...
Archive already exists at /home/dwi/.cache/nodegui-mini-qt-nodejs/5.14.1-0-202001240953qtbase-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z. Skipping download....
Extracting /home/dwi/.cache/nodegui-mini-qt-nodejs/5.14.1-0-202001240953qtbase-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z to /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/nodegui/miniqt ...
Error: Exited with code 2
    at ChildProcess.<anonymous> (/home/dwi/Kerja/nodegui-starter/node_modules/7zip-min/index.js:64:19)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.30.1 setupqt: `cross-env node ./scripts/setupMiniQt.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nodegui/nodegui@0.30.1 setupqt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dwi/.npm/_logs/2021-03-10T17_36_11_197Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.30.1 postinstall: `cross-env npm run setupqt && (node ./scripts/skip.js || npm run build:addon)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nodegui/nodegui@0.30.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dwi/.npm/_logs/2021-03-10T17_36_11_547Z-debug.log
```
how to solve it?

i run on manjaro linux

**Comment by a7ul** [comment]
Hmm, looks like the downloaded zip is somehow incomplete. 
Could you try deleting /home/dwi/.cache/nodegui-mini-qt-nodejs

and also your node_modules folder and try npm install again ?

**Comment by x1yy** [comment]
here is the log after i delete the cache
```
> @nodegui/qode@2.1.0 postinstall /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/qode
> node install.js

Cached archive already exists at /home/dwi/.cache/qode-nodejs/qode-linux-x64-v2.1.0.tar.gz. Skipping download....
Extracting /home/dwi/.cache/qode-nodejs/qode-linux-x64-v2.1.0.tar.gz to /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/qode/binaries ...
Qode was setup successfully at : /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/qode/binaries

> @nodegui/nodegui@0.30.1 postinstall /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/nodegui
> cross-env npm run setupqt && (node ./scripts/skip.js || npm run build:addon)


> @nodegui/nodegui@0.30.1 setupqt /home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/nodegui
> cross-env node ./scripts/setupMiniQt.js

Minimal Qt 5.14.1 setup:
/home/dwi/Kerja/nodegui-starter/node_modules/progress/lib/node-progress.js:160
  complete = Array(Math.max(0, completeLength + 1)).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (/home/dwi/Kerja/nodegui-starter/node_modules/progress/lib/node-progress.js:160:14)
    at ProgressBar.tick (/home/dwi/Kerja/nodegui-starter/node_modules/progress/lib/node-progress.js:97:8)
    at PassThrough.<anonymous> (/home/dwi/Kerja/nodegui-starter/node_modules/@nodegui/artifact-installer/dist/downloader.js:54:49)
    at PassThrough.emit (events.js:327:22)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at PassThrough.Readable.push (internal/streams/readable.js:223:10)
    at PassThrough.Transform.push (internal/streams/transform.js:166:32)
    at PassThrough.afterTransform (internal/streams/transform.js:101:10)
    at PassThrough._transform (internal/streams/passthrough.js:46:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.30.1 setupqt: `cross-env node ./scripts/setupMiniQt.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nodegui/nodegui@0.30.1 setupqt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dwi/.npm/_logs/2021-03-10T17_57_46_647Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.30.1 postinstall: `cross-env npm run setupqt && (node ./scripts/skip.js || npm run build:addon)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nodegui/nodegui@0.30.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dwi/.npm/_logs/2021-03-10T17_57_47_213Z-debug.log
```

**Comment by x1yy** [comment]
i made it working by using qt mirror option
```
QT_LINK_MIRROR=https://qt-mirror.dannhauer.de npm install
```
