### ISSUE TITLE
windows npm install error node_modules\progress\lib\node-progress.js:161

### ISSUE THREAD

**Issue by razr001** [nodegui/nodegui-starter#211]
- windows 10
- windows PowerShell
- Node v12.20.1
- Visual Studio 2019

```js
Minimal Qt 5.14.1 setup:
Archive already exists at C:\Users\Administrator\AppData\Local\nodegui-mini-qt-nodejs\Cache\5.14.1-0-202001240957qttools-Windows-Windows_10-MSVC2017-Windows-Windows_10-X86_64.7z. Skipping download....
Extracting C:\Users\Administrator\AppData\Local\nodegui-mini-qt-nodejs\Cache\5.14.1-0-202001240957qttools-Windows-Windows_10-MSVC2017-Windows-Windows_10-X86_64.7z to E:\dev\shoesUI\react-nodegui-starter\node_modules\@nodegui\nodegui\miniqt ...
E:\dev\shoesUI\react-nodegui-starter\node_modules\progress\lib\node-progress.js:161
  incomplete = Array(Math.max(0, width - completeLength + 1)).join(this.chars.incomplete);
               ^

RangeError: Invalid array length
    at ProgressBar.render (E:\dev\shoesUI\react-nodegui-starter\node_modules\progress\lib\node-progress.js:161:16)
    at ProgressBar.tick (E:\dev\shoesUI\react-nodegui-starter\node_modules\progress\lib\node-progress.js:97:8)
    at PassThrough.<anonymous> (E:\dev\shoesUI\react-nodegui-starter\node_modules\@nodegui\artifact-installer\dist\downloader.js:54:49)
    at PassThrough.emit (events.js:326:22)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at PassThrough.Readable.push (_stream_readable.js:213:10)
    at PassThrough.Transform.push (_stream_transform.js:152:32)
    at PassThrough.afterTransform (_stream_transform.js:96:10)
    at PassThrough._transform (_stream_passthrough.js:46:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.30.1 setupqt: `cross-env node ./scripts/setupMiniQt.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/nodegui@0.30.1 setupqt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\npm\cache\_logs\2021-05-19T06_03_07_235Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
```

**Comment by a7ul** [comment]
Could you try this again. 
Also node v12 is no longer supported. You can use the latest Node v16 now
