### ISSUE TITLE
No linux arm64 support

### ISSUE THREAD

**Issue by darkoverlordofdata** [nodegui/nodegui-starter#217]
duplicate of the issue #1 I filed with quodejs.  Sorry, not sure which of these would get looked at.
npm install fails on debian 11 (bullseye) with

�[K�[?25hnpm ERR! code 1
npm ERR! path /home/darko/GitHub/nodegui-starter/node_modules/@nodegui/qode
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Error while setting up Qode:  Error: Error while downloading Qode v16.4.0:https://github.com/nodegui/qodejs/releases/download/v16.4.0-qode/v16.4.0-qode-linux-arm64.tar.gz. Not Found
npm ERR!     at download (/home/darko/GitHub/nodegui-starter/node_modules/@nodegui/qode/src/downloader.js:33:11)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async setupQode (/home/darko/GitHub/nodegui-starter/node_modules/@nodegui/qode/src/setup.js:19:3)
npm ERR!     at async main (/home/darko/GitHub/nodegui-starter/node_modules/@nodegui/qode/install.js:7:5)

**Comment by wellitsucks** [comment]
this issue still exist :/
