### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by dani69654** [nodegui/nodegui-starter#233]
Following the steps here: https://docs.nodegui.org/#quick-start <br />

```bash
git clone https://github.com/nodegui/nodegui-starter
cd nodegui-starter
npm install
npm start
```

Throws error on `npm start`

```
Error: dlopen(/Users/*/*/Coding/nodegui-starter/dist/nodegui_core-11b86f3fc08e20c5e2f70d6cf217ccd5.node, 0x0001): Library not loaded: @rpath/QtSvg.framework/Versions/5/QtSvg
  Referenced from: <C709F5BC-C745-31F0-B913-EAFDC85C3C00> /Users/*/*/Coding/nodegui-starter/dist/nodegui_core-11b86f3fc08e20c5e2f70d6cf217ccd5.node
  Reason: tried: '/Users/runner/work/nodegui/nodegui/miniqt/5.15.2/clang_64/lib/QtSvg.framework/Versions/5/QtSvg' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/nodegui/nodegui/miniqt/5.15.2/clang_64/lib/QtSvg.framework/Versions/5/QtSvg' (no such file), '/Users/runner/work/nodegui/nodegui/miniqt/5.15.2/clang_64/lib/QtSvg.framework/Versions/5/QtSvg' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/nodegui/nodegui/miniqt/5.15.2/clang_64/lib/QtSvg.framework/Versions/5/QtSvg' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/QtSvg.framework/Versions/5/QtSvg' (no such file), '/Users/runner/work/nodegui/nodegui/miniqt/5.15.2/clang_64/lib/QtSvg.framework/Versions/5/QtSvg' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/nodegui/nodegui/miniqt/5.15.2/clang_64/lib/QtSvg.framework/Versions/5/QtSvg' (no such file), '/Users/runner/work/nodegui/nodegui/miniqt/5.15.2/clang_64/lib/QtSvg.framework/Versions/5/QtSvg' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/nodegui/nodegui/miniqt/5.15.2/clang_64/lib/QtSvg.framework/Versions/5/QtSvg' (no such file), '/Library/Frameworks/QtSvg.framework/Versions/5/QtSvg' (no such file), '/System/Library/Frameworks/QtSvg.framework/Versions/5/QtSvg' (no such file, not in dyld cache)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1154:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at eval (webpack://nodegui-starter/./node_modules/@nodegui/nodegui/build/Release/nodegui_core.node?:1:18)
    at Object../node_modules/@nodegui/nodegui/build/Release/nodegui_core.node (/Users/*/*/Coding/nodegui-starter/dist/index.js:2632:1)
    at __webpack_require__ (/Users/*/*/Coding/nodegui-starter/dist/index.js:3139:42)
    at eval (webpack://nodegui-starter/./node_modules/@nodegui/nodegui/dist/lib/utils/addon.js?:3:15)
    at Object../node_modules/@nodegui/nodegui/dist/lib/utils/addon.js (/Users/*/*/Coding/nodegui-starter/dist/index.js:2549:1) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by baradhili** [comment]
same here...

**Comment by lafkpages** [comment]
Getting the same on MacOS.

**Comment by KettLovahr** [comment]
A different, but likely related error on Linux:

```
/home/kett/Documents/Project/Other/JS/nodegui-starter/node_modules/@nodegui/qode/binaries/qode: symbol lookup error: /home/kett/Documents/Project/Other/JS/nodegui-starter/dist/nodegui_core-290f6c2c05e3b47bcedc55c3bd1078e0.node: undefined symbol: _ZdlPvm, version Qt_5
```

Seems to have to do with [this issue](https://github.com/nodegui/nodegui/issues/994). Changing the nodegui version as a comment on the linked issue says allows it to run normally.

This was a very bad first impression, though. This demo should probably be updated so that it works.

**Comment by sedwards2009** [comment]
See #235
